-- 삭제 데이터 테이블(BATCH_DEV_1 에 CREATE)

CREATE TABLE GB_TB_EXC_REC_REP
    (
        EXC_PER_REP_SEQ VARCHAR2(4) NOT NULL,
        EXC_PER_REP_NAME VARCHAR2(40) NULL,
        PROGRS_STAT_CODE CHAR(4) NULL,
        EXC_DATE DATE NULL,
        DEL_DATE DATE NULL,
        DEL_ID VARCHAR2(12) NULL,
        CONSTRAINT PK_GB_TB_EXC_REC_REP PRIMARY KEY (EXC_PER_REP_SEQ)
    );

COMMENT ON TABLE GB_TB_EXC_REC_REP IS '수행실적신고 테이블';
COMMENT ON COLUMN GB_TB_EXC_REC_REP.EXC_PER_REP_SEQ IS '수행실적신고일련번호';
COMMENT ON COLUMN GB_TB_EXC_REC_REP.EXC_PER_REP_NAME IS '수행실적신고명';
COMMENT ON COLUMN GB_TB_EXC_REC_REP.PROGRS_STAT_CODE IS '진행상태코드';
COMMENT ON COLUMN GB_TB_EXC_REC_REP.EXC_DATE IS '수행일자';
COMMENT ON COLUMN GB_TB_EXC_REC_REP.DEL_DATE IS '삭제일자';
COMMENT ON COLUMN GB_TB_EXC_REC_REP.DEL_ID IS '삭제자ID';
--

CREATE TABLE GB_TB_PER_REP
    (
        EXC_PER_REP_SEQ VARCHAR2(4) NOT NULL,
        PER_NO NUMBER(12,0) NOT NULL,
        SERVC_NAME VARCHAR2(40) NULL,
        SERVC_SE_CODE CHAR(4) NULL,
        CNTRCT_AMOUNT NUMBER(20,2) NULL,
        CHARGER_NAME VARCHAR2(12) NULL,
        SERVC VARCHAR2(50) NULL,
        DEL_DATE DATE NULL,
        DEL_ID VARCHAR2(12) NULL,
        CONSTRAINT PK_GB_TB_PER_REP PRIMARY KEY (EXC_PER_REP_SEQ, PER_NO),
        CONSTRAINT FK_GB_TB_PER_REP FOREIGN KEY (EXC_PER_REP_SEQ) REFERENCES GB_TB_EXC_REC_REP(EXC_PER_REP_SEQ) ON DELETE CASCADE
    );

COMMENT ON TABLE GB_TB_PER_REP IS '실적신고 테이블';
COMMENT ON COLUMN GB_TB_PER_REP.EXC_PER_REP_SEQ IS '수행실적신고일련번호';
COMMENT ON COLUMN GB_TB_PER_REP.PER_NO IS '실적순서번호';
COMMENT ON COLUMN GB_TB_PER_REP.SERVC_NAME IS '용역명';
COMMENT ON COLUMN GB_TB_PER_REP.SERVC_NAME IS '용역구분코드';
COMMENT ON COLUMN GB_TB_PER_REP.CNTRCT_AMOUNT IS '계약금액';
COMMENT ON COLUMN GB_TB_PER_REP.CHARGER_NAME IS '담당자명';
COMMENT ON COLUMN GB_TB_PER_REP.SERVC IS '용역내용';
COMMENT ON COLUMN GB_TB_PER_REP.DEL_DATE IS '삭제일자';
COMMENT ON COLUMN GB_TB_PER_REP.DEL_ID IS '삭제자ID';
--
CREATE TABLE GB_TB_EQPMN_REP
    (
        EXC_PER_REP_SEQ VARCHAR2(4) NOT NULL,
        EQPMN_NO VARCHAR2(14) NOT NULL,
        EQPMN_NAME VARCHAR2(12) NULL,
        STNDRD VARCHAR2(12) NULL,
        REG_NO NUMBER(12,0) NULL,
        GRAD_CODE CHAR(4) NULL,
        DEL_DATE DATE NULL,
        DEL_ID VARCHAR2(12) NULL,
        CONSTRAINT PK_GB_TB_EQPMN_REP PRIMARY KEY (EXC_PER_REP_SEQ, EQPMN_NO),
        CONSTRAINT FK_GB_TB_EQPMN_REP FOREIGN KEY (EXC_PER_REP_SEQ) REFERENCES GB_TB_EXC_REC_REP(EXC_PER_REP_SEQ) ON DELETE CASCADE
    );

COMMENT ON TABLE GB_TB_EQPMN_REP IS '장비신고 테이블';
COMMENT ON COLUMN GB_TB_EQPMN_REP.EXC_PER_REP_SEQ IS '수행실적신고일련번호';
COMMENT ON COLUMN GB_TB_EQPMN_REP.EQPMN_NO IS '장비순서번호';
COMMENT ON COLUMN GB_TB_EQPMN_REP.EQPMN_NAME IS '장비명';
COMMENT ON COLUMN GB_TB_EQPMN_REP.STNDRD IS '규격';
COMMENT ON COLUMN GB_TB_EQPMN_REP.REG_NO IS '등록번호';
COMMENT ON COLUMN GB_TB_EQPMN_REP.GRAD_CODE IS '등급코드';
COMMENT ON COLUMN GB_TB_EQPMN_REP.DEL_DATE IS '삭제일자';
COMMENT ON COLUMN GB_TB_EQPMN_REP.DEL_ID IS '삭제자ID';