spring:
  profiles:
    active: local

logging:
  level:
    org.springframework.batch: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG

    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: DEBUG

