server:
  servlet:
    context-path: /
  port: 8081

  # mybatis 설정
mybatis:
  # 매퍼 xml의 위치-classpath:/ 리소스 폴더의 하위를 나타냄
  mapper-locations: classpath:/egovframework/mapper/**/*.xml
  # 단축명으로 사용할 클래스의 패키지명
  type-aliases-package: com.siso.web.*.model
  configuration:
    map-underscore-to-camel-case: false
    default-fetch-size: 3000
    default-statement-timeout: 60
    jdbc-type-for-null: "NULL"
    
cors:
  allowed-origin: "http://localhost:3000"

code-id:
  eqpmnGrade: "PMS002"
  serviceType: "PMS003"

spring:
  batch:
    # 애플리케이션이 실행될 때, Batch 가 무조건 실행되는 것을 방지환다.
    job:
      enabled: false
    initialize-schema: always

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:oracle:thin:@127.0.0.1:1522:xe
    username: dev_1
    password: 1234

  datasource-batch:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:oracle:thin:@127.0.0.1:1522:xe
    username: batch_dev_1
    password: 1234